kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: "{{namespace}}"
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: "{{namespace}}"
  labels:
    app: postgres
spec:
  storageClassName: manual
  volumeName: postgres-pv-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi