apiVersion: v1
kind: Namespace
metadata:
  name: "{{namespace}}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-config
  namespace: {{namespace}}
  labels:
     app: sftp
data:
  USER: sftpuser
  region: dev
  path_to_private_key_file: .ssh/ssh_host_ed25519_key
  private_key_passphrase: test
  sftp_user: sftpuser 
---
#postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  namespace: "{{namespace}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
        - name: ssh-keys-vol
          secret:
            secretName: sftp-ssh-secrets
            defaultMode: 0600 
      imagePullSecrets:
      - name: {{image-secret-name}}
      containers:
        - name: sftp-container
          image: "{{registry-name}}atmoz/sftp:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 22
          args: ["sftpuser::1000"]
          envFrom:
            - configMapRef:
                name: sftp-config
          volumeMounts:
              - name: ssh-keys-vol
                readOnly: true
                mountPath: "/home/sftpuser/.ssh/keys"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          